version: '3'

services:
  db:
    container_name: "ee_postgres"
    image: postgres
    volumes:
      - myDbData:/var/lib/postgresql/data
    ports:
      - "0.0.0.0:5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code:Z
    ports:
      - "8000:8000"
    depends_on:
      - db
volumes:
  myDbData: